name: Build Docker image

# Triggers the workflow when pushing new tags
on:
  push:
    tags:
    - '*'

jobs:
  build-code:
    environment: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        run: |
          echo "ModuleVersion=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: CODE_SERVER_VERSION=${{ env.ModuleVersion }}
          tags: |
            whyvra/code-server-dotnet:latest
            whyvra/code-server-dotnet:${{ env.ModuleVersion }}
